#!/bin/bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

source ./script/helper

echo ''

install_xcode() {
    if test ! $(command -v xcodebuild); then
        user 'Install Xcode first: https://itunes.apple.com/ch/app/xcode/id497799835?l=en&mt=12'
        open 'https://itunes.apple.com/ch/app/xcode/id497799835?l=en&mt=12'
        info "Open and accept the terms, then press enter to continue"

        read nothing
    fi
}

install_ohmyzsh() {
    info "Installing oh-my-zsh"
    if [ -z ${ZSH+x} ]; then

        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

        source ~/.zshrc
        success "oh-my-zsh installed"
    else
        info "the \$ZSH var is exported."
    fi
}

install_dotfiles() {
    info 'Installing the dotfiles'

    local overwrite_all=false backup_all=false skip_all=false

    for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*'); do
        dst="$HOME/.$(basename "${src%.*}")"
        link_file "$src" "$dst"
    done
}

install_xdg_dotfiles() {
    info 'Installing XDG config dotfiles'

    local overwrite_all=false backup_all=false skip_all=false

    # Process each XDG directory type
    for xdg_name in config data cache state; do
        local src_dir="$DOTFILES_ROOT/xdg/$xdg_name"
        local dst_base=""

        # Map directory names to XDG environment variables
        case "$xdg_name" in
            config) dst_base="${XDG_CONFIG_HOME:-$HOME/.config}" ;;
            data)   dst_base="${XDG_DATA_HOME:-$HOME/.local/share}" ;;
            cache)  dst_base="${XDG_CACHE_HOME:-$HOME/.cache}" ;;
            state)  dst_base="${XDG_STATE_HOME:-$HOME/.local/state}" ;;
        esac

        if [ -d "$src_dir" ]; then
            # Use for loop (like install_dotfiles) to keep variables in scope
            for src in $(find "$src_dir" -type f); do
                local relative_path="${src#$src_dir/}"
                local dst="$dst_base/$relative_path"

                # Create parent directory if needed
                mkdir -p "$(dirname "$dst")"

                link_file "$src" "$dst"
            done
        fi
    done
}

install_fonts() {
    local overwrite_all=false backup_all=false skip_all=false

    info 'Installing the fonts'

    FONT_DIR="~/Library/Fonts"
    find -H "$DOTFILES_ROOT" -maxdepth 4 \( -iname \*.otf -o -iname \*.ttf \) -not -path '*.git*' | while read font; do
        # dst="$FONT_DIR/$(basename "${font}")"
        # link_file "$font" "$dst"

        # open the font as adding them to the font folder is not enough...
        open "$font"
    done

    success "Fonts installed"
}

install_dependencies() {
    # Install all other dependencies
    info "Installing dependencies"
    if source bin/dot | while read -r data; do info "$data"; done; then
        success "Dependencies installed"
    else
        fail "Error installing dependencies"
    fi
}

install_xcode
install_fonts
install_ohmyzsh
install_dotfiles
install_xdg_dotfiles
install_dependencies

echo ''
echo '  All installed!'
