#!/bin/bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

source ./script/helper

echo ''

install_xcode() {
    if test ! $(command -v xcodebuild); then
        user 'Install Xcode first: https://itunes.apple.com/ch/app/xcode/id497799835?l=en&mt=12'
        open 'https://itunes.apple.com/ch/app/xcode/id497799835?l=en&mt=12'
        info "Open and accept the terms, then press enter to continue"

        read nothing
    fi
}

install_ohmyzsh() {
    info "Installing oh-my-zsh"
    if [ -z ${ZSH+x} ]; then

        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

        source ~/.zshrc
        success "oh-my-zsh installed"
    else
        info "the \$ZSH var is exported."
    fi
}

install_dotfiles() {
    info 'Installing the dotfiles'

    local overwrite_all=false backup_all=false skip_all=false

    for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*'); do
        dst="$HOME/.$(basename "${src%.*}")"
        link_file "$src" "$dst"
    done
}

install_fonts() {
    local overwrite_all=false backup_all=false skip_all=false

    info 'Installing the fonts'

    FONT_DIR="~/Library/Fonts"
    find -H "$DOTFILES_ROOT" -maxdepth 4 \( -iname \*.otf -o -iname \*.ttf \) -not -path '*.git*' | while read font; do
        # dst="$FONT_DIR/$(basename "${font}")"
        # link_file "$font" "$dst"

        # open the font as adding them to the font folder is not enough...
        open "$font"
    done

    success "Fonts installed"
}

install_dependencies() {
    # Install all other dependencies
    info "Installing dependencies"
    if source bin/dot | while read -r data; do info "$data"; done; then
        success "Dependencies installed"
    else
        fail "Error installing dependencies"
    fi
}

install_xcode
install_fonts
install_ohmyzsh
install_dotfiles
install_dependencies

echo ''
echo '  All installed!'
